# GAEA Halloween
type=item
items=minecraft\:diamond_shovel
texture=gaea_halloween
nbt.display.Name=GAEA Halloween
nbt.display.Lore.8=\u7279\u5225\u306aGAEA\u3092\u3042\u306a\u305f\u306b\u2661
nbt.display.Lore.10=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aSpecialBoyWaka