# 通常GT
type=item
items=minecraft:diamond_pickaxe
texture=thanatos
nbt.display.Name=THANATOS
nbt.display.Lore.1=iregex:(最大体力\\(中\\)増加|左クリックで1スタック取り出し)
enchantments=efficiency silk_touch
enchantmentLevels=10 1
weight=-1
