# APOLLO 5thAnniv. 2021
type=item
items=minecraft:diamond_helmet
texture=diamond_helmet
nbt.display.Name=APOLLO 5thAnniv.
nbt.display.Lore.*=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005\uFF1Anubasu
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7