# SERRULATA 2024春
type=item
items=minecraft:diamond_axe
texture=serrulata
nbt.display.Name=SERRULATA
nbt.display.Lore.1=\u8010\u4e45\u7121\u9650
nbt.display.Lore.4=\u300c\u30b5\u30af\u30e9\u54b2\u304f\u300d
nbt.display.Lore.6=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005: ploptaw