# APOLLO 10thAnniv. 2026
type=item
items=minecraft:netherite_helmet
texture=netherite_helmet
nbt.display.Name=APOLLO 10thAnniv.
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7
