# 通常GT
type=item
items=minecraft:bow
texture.bow=artemis_standby
texture.bow_pulling_0=artemis_pulling_0
texture.bow_pulling_1=artemis_pulling_1
texture.bow_pulling_2=artemis_pulling_2
nbt.display.Name=ARTEMIS
enchantments=flame infinity mending power unbreaking
enchantmentLevels=1 1 1 10 10