type=item
items=shield
model=./arthur_w.json
model.shield_blocking=./arthur_w_blocking.json
nbt.display.Name=ARTHUR 10thAnniv. / White
nbt.display.Lore.10=10周年記念で獲得できた
nbt.display.Lore.11=特別なARTHURです。
nbt.display.Lore.13=テクスチャ製作者：ploptaw
