type=item
items=minecraft:netherite_pickaxe
texture=thanatos
nbt.display.Name=THANATOS 10thAnniv.
nbt.display.Lore.7=10周年記念で獲得できた
nbt.display.Lore.8=特別なTHANATOSです。
nbt.display.Lore.10=テクスチャ製作者：ploptaw
