type=item
items=shield
model=./arthur_b.json
model.shield_blocking=./arthur_b_blocking.json
nbt.display.Name=ARTHUR 10thAnniv. / Black
nbt.display.Lore.10=10周年記念で獲得できた
nbt.display.Lore.11=特別なARTHURです。
nbt.display.Lore.13=テクスチャ製作者：ploptaw
