# HERCULES 6thAnniv. 2022
type=item
items=minecraft:diamond_boots
texture=diamond_boots
nbt.display.Name=HERCULES 6thAnniv.
enchantments=depth_strider feather_falling mending protection unbreaking
enchantmentLevels=3 7 1 6 8
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aploptaw, aluM_8bit