# THANATOS 6thAnniv. ブルーハワイ 2022
type=item
items=minecraft:diamond_pickaxe
texture=thanatos6
nbt.display.Name=THANATOS 6thAnniv.
nbt.display.Lore.*=iregex:\u6240\u6709\u8005\uFF1A[stuvw].*
enchantments=efficiency silk_touch
enchantmentLevels=10 1
nbt.display.Lore.7=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331