# THANATOS Spring2022
type=item
items=minecraft\:diamond_pickaxe
texture=diamond_pickaxe
nbt.display.Name=THANATOS Spring
nbt.display.Lore.8=\u7279\u5225\u306aTHANATOS\u3092\u3042\u306a\u305f\u306b\u2661