# 通常GT
type=item
items=minecraft:diamond_helmet
texture=diamond_helmet
nbt.display.Name=APOLLO
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7
weight=-1