# 通常GT
type=item
items=minecraft:diamond_helmet
texture=diamond_helmet
nbt.display.Name=APOLLO
nbt.display.Lore.1=iregex:(装備中は満腹度自動回復と|右クリックで1個取り出し)
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7
weight=-1
