type=item
items=minecraft:elytra
texture.broken_elytra=elytra_broken
damage=431-
nbt.display.Name=ICARUS
nbt.display.Lore.1=iregex:(装備中は火炎耐性が付与されます|右クリックで1個取り出し)
enchantments=mending protection unbreaking
enchantmentLevels=1 7 10
weight=-1
