# GAEA 6thAnniv. グレープ 2022
type=item
items=minecraft:diamond_shovel
texture=gaea7
nbt.display.Name=GAEA 6thAnniv.
enchantments=efficiency silk_touch
enchantmentLevels=10 1
nbt.display.Lore.7=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331