# °*✧ꕤ≡≡魔法の杖≡≡ꕤ✧*°
type=item
items=minecraft:carrot_on_a_stick
texture=carrot_on_a_stick
nbt.display.Name=iregex:.*\u9b54\u6cd5\u306e\u6756.*
nbt.display.Lore.0=iregex:.*\u50d5\u3068\u5951\u7d04\u3057\u3066.*
nbt.display.Lore.1=iregex:.*\u9b54\u6cd5\u5c11\u5973\u306b\u306a\u3063\u3066\u3088\uff01.*