# ARTEMIS 7thAnniv. 2023
type=item
items=minecraft:bow
texture.bow=bow_standby
texture.bow_pulling_0=bow_pulling_0
texture.bow_pulling_1=bow_pulling_1
texture.bow_pulling_2=bow_pulling_2
nbt.display.Name=ARTEMIS 7thAnniv.
nbt.display.Lore.9=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331