type=armor
items=minecraft:diamond_boots
texture.diamond_layer_1=diamond_layer_1
texture.diamond_layer_2=diamond_layer_2
nbt.display.Name=HERCULES
nbt.display.Lore.1=iregex:(装備中は跳躍力が付与されます|右クリックで1個取り出し)
weight=-1
