# 通常GT
type=item
items=minecraft:diamond_boots
texture=diamond_boots
nbt.display.Name=HERCULES
enchantments=depth_strider feather_falling mending protection unbreaking
enchantmentLevels=3 7 1 6 8
weight=-1