# 通常GT
type=item
items=minecraft:diamond_boots
texture=diamond_boots
nbt.display.Name=HERCULES
nbt.display.Lore.1=iregex:(装備中は跳躍力が付与されます|左クリックで1スタック取り出し)
enchantments=depth_strider feather_falling mending protection unbreaking
enchantmentLevels=3 7 1 6 8
weight=-1
