# ARTEMIS 6thAnniv.
type=item
items=minecraft:bow
texture.bow=bow_standby
texture.bow_pulling_0=bow_pulling_0
texture.bow_pulling_1=bow_pulling_1
texture.bow_pulling_2=bow_pulling_2
nbt.display.Name=ARTEMIS 6thAnniv.
enchantments=flame infinity mending power unbreaking
enchantmentLevels=1 1 1 10 10
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aArgon_7270