type=armor
items=minecraft:netherite_boots
texture.netherite_layer_1=netherite_layer_1
texture.netherite_layer_2=netherite_layer_2
nbt.display.Name=HERCULES 10thAnniv.
nbt.display.Lore.*=10周年記念で獲得できた
nbt.display.Lore.*=特別なHERCULESです。
nbt.display.Lore.*=テクスチャ製作者：ploptaw
