type=item
items=minecraft:netherite_boots
texture=netherite_boots
nbt.display.Name=HERCULES 10thAnniv.
nbt.display.Lore.*=10周年記念で獲得できた
nbt.display.Lore.*=特別なHERCULESです。
nbt.display.Lore.*=テクスチャ製作者：ploptaw
