# 銅の王冠
type=item
items=minecraft:bedrock
nbt.display.Name=\u9285\u306E\u738B\u51A0
nbt.display.Lore.2=3\u4f4d\u30c1\u30fc\u30e0\u306e\u8a3c
nbt.display.Lore.4=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005: nubasu
model=./bronze_crown.json