# 銀の王冠
type=item
items=minecraft:bedrock
nbt.display.Name=\u9280\u306E\u738B\u51A0
nbt.display.Lore.2=\u6e96\u512a\u52dd\u30c1\u30fc\u30e0\u306e\u8a3c
nbt.display.Lore.4=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005: nubasu
model=./silver_crown.json