# NARUTO REMAKE II ハロウィンイベ2021景品
type=item
items=minecraft\:shears
texture=naruto_remake2
nbt.display.Name=NARUTO REMAKE II
nbt.display.Lore.*=iregex:\u30c6\u30af\u30b9\u30c1\u30e3\u539f\u6848\u8005(\uff1akinton|: kinton)