# PLUTO 4thAnniv. 2020
type=item
items=minecraft:diamond_sword
texture=diamond_sword
nbt.display.Name=PLUTO 4thAnniv.
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1a19moon
enchantments=looting mending sharpness unbreaking
enchantmentLevels=5 1 10 10