# APOLLO 4thAnniv. 2020
type=item
items=minecraft:diamond_helmet
texture=diamond_helmet
nbt.display.Name=APOLLO 4thAnniv.
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1a19moon
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7