# ICARUS 6thAnniv. 2022
type=item
items=minecraft:elytra
texture=item
damage=-430
nbt.display.Name=ICARUS 6thAnniv.
enchantments=mending protection unbreaking
enchantmentLevels=1 7 10
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aploptaw, aluM_8bit