type=item
items=minecraft:elytra
texture.broken_elytra=item_broken
damage=431-
nbt.display.Name=ICARUS 6thAnniv.
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aploptaw, aluM_8bit