type=item
items=minecraft:elytra
texture.broken_elytra=item_broken
damage=431-
nbt.display.Name=ICARUS 10thAnniv.
nbt.display.Lore.*=10周年記念で獲得できた
nbt.display.Lore.*=特別なICARUSです。
nbt.display.Lore.*=テクスチャ製作者：ploptaw
