type=armor
items=minecraft:diamond_leggings
texture.diamond_layer_1=diamond_layer_1
texture.diamond_layer_2=diamond_layer_2
nbt.display.Name=NEMESIS
nbt.display.Lore.1=iregex:(ダメージを受けると|左クリックで1スタック取り出し)
weight=-1
