# 通常GT
type=item
items=minecraft:diamond_leggings
texture=diamond_leggings
nbt.display.Name=NEMESIS
nbt.display.Lore.1=iregex:(ダメージを受けると|左クリックで1スタック取り出し)
enchantments=mending protection unbreaking
enchantmentLevels=1 7 10
weight=-1
