type=armor
items=minecraft:diamond_helmet
texture.diamond_layer_1=diamond_layer_1
texture.diamond_layer_2=diamond_layer_2
nbt.display.Name=APOLLO 6thAnniv.
nbt.display.Lore.7=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aploptaw, aluM_8bit