type=item
items=minecraft:netherite_leggings
texture=netherite_leggings
nbt.display.Name=NEMESIS 10thAnniv.
nbt.display.Lore.*=10周年記念で獲得できた
nbt.display.Lore.*=特別なNEMESISです。
nbt.display.Lore.*=テクスチャ製作者：ploptaw
