# ATHENA
type=item
items=minecraft:bow
texture.bow=athena
texture.bow_pulling_0=athena_pulling_0
texture.bow_pulling_1=athena_pulling_1
texture.bow_pulling_2=athena_pulling_2
nbt.display.Name=ATHENA
nbt.display.Lore.1=打つと花火があがります
nbt.display.Lore.2=矢がHITすると落雷を発生させます