# NARUTO REMAKE I ハロウィンイベ2021景品
type=item
items=minecraft\:shears
texture=naruto_remake
nbt.display.Name=NARUTO REMAKE I
nbt.display.Lore.3=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aSpecialBoyWaka