# TITAN Replica II 2022
type=item
items=minecraft\:diamond_axe
texture=diamond_axe
nbt.display.Name=TITAN Replica II
nbt.display.Lore.6=\u7279\u5225\u306aTITAN\u3092\u3042\u306a\u305f\u306b\u2661
nbt.display.Lore.8=\u30c6\u30af\u30b9\u30c1\u30e3\u539f\u6848\u8005: shirotubu