# PLUTO Halloween Replica
type=item
items=minecraft:diamond_sword
texture=pluto_halloween
nbt.display.Name=PLUTO Halloween Replica
nbt.display.Lore.1=regex:\\d{4,}\u30cf\u30ed\u30a6\u30a3\u30f3\u30a4\u30d9\u30f3\u30c8\u7279\u5225\u9650\u5b9a\u54c1
nbt.display.Lore.2=\u7279\u5225\u306aPLUTO\u3092\u3042\u306a\u305f\u306b\u2661
nbt.display.Lore.4=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aSpecialBoyWaka