# 通常GT
type=item
items=minecraft:diamond_sword
texture=pluto
nbt.display.Name=PLUTO
nbt.display.Lore.1=iregex:(攻撃時に敵をウィザー状態にします|右クリックで1個取り出し)
enchantments=looting mending sharpness unbreaking
enchantmentLevels=5 1 10 10
weight=-1
