# がくせいなふく（下） spring2022
type=item
items=minecraft:chainmail_leggings
texture=item
nbt.display.Name=\u304c\u304f\u305b\u3044\u306a\u3075\u304f\uff08\u4e0b\uff09
nbt.display.Lore.*=iregex:.*\u304a\u82b1\u898b\u30a4\u30d9\u30f3\u30c8.*