# APOLLO 7thAnniv. 2023
type=item
items=minecraft:diamond_helmet
texture=diamond_helmet
nbt.display.Name=APOLLO 7thAnniv.
enchantments=aqua_affinity mending protection respiration unbreaking
enchantmentLevels=1 1 6 3 7
nbt.display.Lore.*=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331