# PLUTO Replica spring2022
type=item
items=minecraft:diamond_sword
texture=diamond_sword
nbt.display.Name=PLUTO Spring Replica
nbt.display.Lore.1=iregex:.*\u304a\u82b1\u898b\u30a4\u30d9\u30f3\u30c8\u7279\u5225\u9650\u5b9a\u54c1
nbt.display.Lore.*=\u7279\u5225\u306aPLUTO\u3092\u3042\u306a\u305f\u306b\u2661
nbt.display.Lore.*=iregex:\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c(\u8005\uff1aB_Makkuro|\u8005: B_Makkuro)