# 立体まいんちゃん
items=minecraft:bedrock
nbt.display.Name=\u7ACB\u4F53\u307E\u3044\u3093\u3061\u3083\u3093
nbt.display.Lore.4=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005: nubasu
model=./minechan_high.json