# HERCULES 7thAnniv. 2023
type=item
items=minecraft:diamond_boots
texture=diamond_boots
nbt.display.Name=HERCULES 7thAnniv.
enchantments=depth_strider feather_falling mending protection unbreaking
enchantmentLevels=3 7 1 6 8
nbt.display.Lore.*=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331