type=item
items=minecraft:bow
texture.bow=artemis_standby
texture.bow_pulling_0=artemis_pulling_0
texture.bow_pulling_1=artemis_pulling_1
texture.bow_pulling_2=artemis_pulling_2
nbt.display.Name=ARTEMIS 10thAnniv.
nbt.display.Lore.8=10周年記念で獲得できた
nbt.display.Lore.9=特別なARTEMISです。
nbt.display.Lore.11=テクスチャ製作者：ploptaw
