# THANATOS 7thAnniv. 2023
type=item
items=minecraft\:diamond_pickaxe
texture=diamond_pickaxe
nbt.display.Name=THANATOS 7thAnniv.
nbt.display.Lore.7=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aploptaw, aluM_8bit