# PLUTO 7thAnniv. 2023
type=item
items=minecraft:diamond_sword
texture=diamond_sword
nbt.display.Name=PLUTO 7thAnniv.
enchantments=looting mending sharpness unbreaking
enchantmentLevels=5 1 10 10
nbt.display.Lore.*=\u30c6\u30af\u30b9\u30c1\u30e3\u88fd\u4f5c\u8005\uff1aInumugi_331