# NEMESIS 7thAnniv. 2023
type=item
items=minecraft:diamond_leggings
texture=diamond_leggings
nbt.display.Name=NEMESIS 7thAnniv.
enchantments=mending protection unbreaking
enchantmentLevels=1 7 10
nbt.display.Lore.*=\u30C6\u30AF\u30B9\u30C1\u30E3\u88FD\u4F5C\u8005：Inumugi_331