name: Release zip file

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set version
        id: version
        run: |
          VERSION=$(grep -o -m 1 -E "(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?" UpdateLog.txt)
          echo ::set-output name=version::$VERSION
          echo "Version: $VERSION"
        
      - name: Zip files
        run: zip -r seichi_tex_${{ steps.version.outputs.version }}.zip *

      - name: Send a zip to server
        run: echo 'Unimplemnted.'
