name: Release zip file

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set versions
        id: versions
        run: |
          OLD_VERSION=$(grep -o -m 1 -E "(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?" pack.mcmeta)
          echo ::set-output name=old_version::$OLD_VERSION
          echo "Old Version: $OLD_VERSION"
          NEW_VERSION=$(grep -o -m 1 -E "(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?" UpdateLog.txt)
          echo ::set-output name=new_version::$NEW_VERSION
          echo "New Version: $NEW_VERSION"
          
      - name: Update pack.mcmeta
        run: sed -i -r 's/(v[0-9]+\.){1}[0-9]+(\.[0-9]+)?/${{ steps.versions.outputs.new_version }}/' pack.mcmeta
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
	  git config --local user.name "github-actions[bot]"

          git add
          git commit -m '[Bump] ${{ steps.versions.outputs.old_version }} -> ${{ steps.versions.outputs.new_version }}'
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/OriginalResourcePack.git HEAD

      - name: Zip files
        run: zip -r seichi_tex_${{ steps.versions.outputs.new_version }}.zip *

      - name: Send a zip to server
        run: echo 'Unimplemnted.'
